--- #YAML:1.0
name:               Conan
version:            undef
abstract:           Building and promoting images a xen cloud
author:
    - Peter Blair <cpan@petermblair.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Rsync:  0.42
    Test::More:   0.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
